//importa el fs
import fs from "fs";

let arr = [
  "en una discoteca",
    "en un cementerio",
    "en el Vaticano",
    "en Júpiter",
    "en una playa paradisíaca",
    "en una montaña nevada",
    "en un bosque encantado",
    "en una isla desierta",
    "en una ciudad bulliciosa",
    "en un pueblo pintoresco",
    "en un castillo medieval",
    "en un submarino sumergido",
    "en una galaxia lejana",
    "en una selva exuberante",
    "en una cueva misteriosa",
    "en un rincón tranquilo",
    "en una pradera verde",
    "en una estación espacial",
    "en una granja rural",
    "en un mercado bullicioso",
    "en un barco pirata",
    "en una mansión embrujada",
    "en una ciudad futurista",
    "en un desierto infinito",
    "en un laberinto subterráneo",
    "en un circo ambulante",
    "en un campo de batalla",
    "en un templo antiguo",
    "en una estación de tren",
    "en una fábrica abandonada",
    "en una carpa de circo",
    "en un parque de diversiones",
    "en un rascacielos gigante",
    "en una base lunar",
    "en una caverna submarina",
    "en una granja de animales",
    "en una cafetería acogedora",
    "en un observatorio astronómico",
    "en un oasis perdido",
    "en una ciudad sumergida",
    "en un palacio real",
    "en una biblioteca antigua",
    "en una estación de esquí",
    "en un laboratorio secreto",
    "en una ciudad submarina",
    "en un parque nacional",
    "en un castillo de cuento de hadas",
    "en un cine lleno de espectadores",
    "en una estación de bomberos",
    "en un centro comercial gigante",
    "en un restaurante de lujo",
    "en una cabaña en el bosque",
    "en un hospital abandonado",
    "en una casa encantada",
    "en un teatro antiguo",
    "en una base secreta",
    "en una mansión elegante",
    "en un club nocturno",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un museo de arte",
    "en una cueva de hielo",
    "en una ciudad en ruinas",
    "en un jardín botánico",
    "en un castillo en el cielo",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en un parque temático",
    "en una base espacial",
    "en un parque acuático",
    "en una ciudad sumergida",
    "en una aldea remota",
    "en un cementerio encantado",
    "en una discoteca futurista",
    "en un mercado callejero",
    "en un castillo encantado",
    "en una estación de tren abandonada",
    "en un laboratorio de experimentos",
    "en un jardín de flores exóticas",
    "en una ciudad flotante",
    "en un parque de dinosaurios",
    "en una playa de arenas blancas",
    "en un observatorio de estrellas",
    "en una granja de cultivo de algodón",
    "en un pueblo medieval",
    "en un castillo de hielo",
    "en una ciudad sumergida",
    "en un templo en la jungla",
    "en una biblioteca antigua",
    "en una isla desierta",
    "en una mansión encantada",
    "en un laboratorio subterráneo",
    "en una ciudad en el espacio",
    "en un circo ambulante",
    "en un bosque misterioso",
    "en un castillo de cuento de hadas",
    "en una estación espacial abandonada",
    "en una base secreta",
    "en un museo de arte",
    "en una estación de bomberos",
    "en una granja de cultivo",
    "en un parque de atracciones",
    "en un campo de fútbol lleno de aficionados",
    "en una base militar",
    "en un zoológico lleno de animales exóticos",
    "en una estación espacial abandonada",
    "en un puente colgante",
    "en una playa desierta",
    "en un acuario submarino",
    "en una plataforma petrolera",
    "en un centro de convenciones",
    "en un cine al aire libre",
    "en una tierra de fantasía",
    "en una estación de esquí",
    "en una ciudad en el espacio",
    "en un laboratorio de alta tecnología",
    "en un río caudaloso",
    "en una mina abandonada",
    "en un tren de alta velocidad",
    "en una iglesia histórica",
    "en una isla tropical",
    "en un observatorio astronómico",
    "en una fábrica de robots",
    "en un castillo medieval",
    "en una ciudad subterránea",
    "en un palacio en el desierto",
    "en una selva misteriosa",
    "en un campo de golf elegante",
    "en el Arco de Triunfo",
    "en París",
    "en la Gran Muralla China",
    "en la Torre Eiffel",
    "en Nueva York",
    "en el Taj Mahal",
    "en el Coliseo Romano",
    "en Londres",
    "en la Estatua de la Libertad",
    "en Río de Janeiro",
    "en la Ópera de Sídney",
    "en Tokio",
    "en la Acrópolis de Atenas",
    "en el Kremlin de Moscú",
    "en Las Vegas",
    "en Machu Picchu",
    "en la Ciudad Prohibida de Pekín",
    "en Dubai",
    "en la Alhambra de Granada",
    "en San Francisco",
    "en la Sagrada Familia de Barcelona",
    "en Ámsterdam",
    "en el Muro de Berlín",
    "en Venecia",
    "en la Plaza Roja de Moscú",
    "en Roma",
    "en la Capilla Sixtina",
    "en la Gran Ópera de Sydney",
    "en la Muralla China",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Coliseo de Roma",
    "en la Torre de Pisa",
    "en el Palacio de Buckingham",
    "en el Louvre de París",
    "en la Catedral de Notre-Dame",
    "en el Monte Fuji",
    "en las Pirámides de Giza",
    "en la Estatua de Cristo Redentor",
    "en la Estatua de la Libertad de Nueva York",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en el Monte Kilimanjaro",
    "en el Burj Khalifa de Dubai",
    "en el Monte Kilimanjaro",
    "en la Torre de Tokio",
    "en el Coliseo Romano",
    "en el Palacio de Buckingham",
    "en el Monte Rushmore",
    "en la Torre de Pisa",
    "en la Plaza de San Marcos",
    "en el Empire State Building",
    "en el Taj Mahal",
    "en el Parque Nacional de Yellowstone",
    "en el Kremlin de Moscú",
    "en el Coliseo Romano",
    "en el Palacio de Versalles",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Templo de la Sagrada Familia",
    "en el Parque Nacional del Gran Cañón",
    "en el Taj Mahal",
    "en la Torre Eiffel de París",
    "en el Gran Palacio de Bangkok",
    "en el Monte Rushmore",
    "en la Gran Muralla China",
    "en el Coliseo Romano",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en el Monte Kilimanjaro",
    "en el Burj Khalifa de Dubai",
    "en el Monte Kilimanjaro",
    "en la Torre de Tokio",
    "en el Coliseo Romano",
    "en el Palacio de Buckingham",
    "en el Monte Rushmore",
    "en la Torre de Pisa",
    "en la Plaza de San Marcos",
    "en el Empire State Building",
    "en el Taj Mahal",
    "en el Parque Nacional de Yellowstone",
    "en el Kremlin de Moscú",
    "en el Coliseo Romano",
    "en el Palacio de Versalles",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Templo de la Sagrada Familia",
    "en el Parque Nacional del Gran Cañón",
    "en el Taj Mahal",
    "en la Torre Eiffel de París",
    "en el Gran Palacio de Bangkok",
    "en el Monte Rushmore",
    "en la Gran Muralla China",
    "en el Coliseo Romano",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en el Monte Kilimanjaro",
    "en el Burj Khalifa de Dubai",
    "en el Monte Kilimanjaro",
    "en la Torre de Tokio",
    "en el Coliseo Romano",
    "en el Palacio de Buckingham",
    "en el Monte Rushmore",
    "en la Torre de Pisa",
    "en la Plaza de San Marcos",
    "en el Empire State Building",
    "en el Taj Mahal",
    "en el Parque Nacional de Yellowstone",
    "en el Kremlin de Moscú",
    "en el Coliseo Romano",
    "en el Palacio de Versalles",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Templo de la Sagrada Familia",
    "en el Parque Nacional del Gran Cañón",
    "en el Taj Mahal",
    "en la Torre Eiffel de París",
    "en el Gran Palacio de Bangkok",
    "en el Monte Rushmore",
    "en la Gran Muralla China",
    "en el Coliseo Romano",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en el Monte Kilimanjaro",
    "en el Burj Khalifa de Dubai",
    "en el Monte Kilimanjaro",
    "en la Torre de Tokio",
    "en el Coliseo Romano",
    "en el Palacio de Buckingham",
    "en el Monte Rushmore",
    "en la Torre de Pisa",
    "en la Plaza de San Marcos",
    "en el Empire State Building",
    "en el Taj Mahal",
    "en el Parque Nacional de Yellowstone",
    "en el Kremlin de Moscú",
    "en el Coliseo Romano",
    "en el Palacio de Versalles",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Templo de la Sagrada Familia",
    "en el Parque Nacional del Gran Cañón",
    "en el Taj Mahal",
    "en la Torre Eiffel de París",
    "en el Gran Palacio de Bangkok",
    "en el Monte Rushmore",
    "en la Gran Muralla China",
    "en el Coliseo Romano",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en el Monte Kilimanjaro",
    "en el Burj Khalifa de Dubai",
    "en el Monte Kilimanjaro",
    "en la Torre de Tokio",
    "en el Coliseo Romano",
    "en el Palacio de Buckingham",
    "en el Monte Rushmore",
    "en la Torre de Pisa",
    "en la Plaza de San Marcos",
    "en el Empire State Building",
    "en el Taj Mahal",
    "en el Parque Nacional de Yellowstone",
    "en el Kremlin de Moscú",
    "en el Coliseo Romano",
    "en el Palacio de Versalles",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Templo de la Sagrada Familia",
    "en el Parque Nacional del Gran Cañón",
    "en el Taj Mahal",
    "en la Torre Eiffel de París",
    "en el Gran Palacio de Bangkok",
    "en el Monte Rushmore",
    "en la Gran Muralla China",
    "en el Coliseo Romano",
    "en el Monte Everest",
    "en el Cristo Redentor de Río de Janeiro",
    "en el Taj Mahal de India",
    "en el Monte Kilimanjaro",
    "en la Muralla China",
    "en la Torre Eiffel de París",
    "en el Palacio de Versalles",
    "en el Coliseo Romano",
    "en el Gran Cañón",
    "en la Gran Muralla China",
    "en la Torre de Londres",
    "en el Empire State Building",
    "en el Monte Everest",
    "en la Torre de Pisa",
    "en el Monte Rushmore",
    "en la Plaza de San Pedro",
    "en la Torre CN de Toronto",
    "en el Palacio de la Alhambra",
    "en el Templo de Angkor Wat",
    "en tu casa",
    "en mi cuarto",
    "dentro de una nevera",
    "en la cocina",
    "en el baño",
    "en el supermercado",
    "en el parque",
    "en la oficina",
    "en el colegio",
    "en la biblioteca",
    "en el gimnasio",
    "en el autobús",
    "en el tren",
    "en el café",
    "en la calle",
    "en la tienda",
    "en el banco",
    "en la farmacia",
    "en el cine",
    "en el restaurante",
    "en la playa",
    "en la montaña",
    "en el aeropuerto",
    "en el centro comercial",
    "en el estadio",
    "en la piscina",
    "en el parque de atracciones",
    "en el jardín",
    "en el hospital",
    "en la plaza",
    "en el teatro",
    "en la gasolinera",
    "en la estación de servicio",
    "en el museo",
    "en la iglesia",
    "en el mercado",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el colegio",
    "en la universidad",
    "en la estación de tren",
    "en el metro",
    "en el parque",
    "en la playa",
    "en la montaña",
    "en el campo",
    "en el centro comercial",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en el aeropuerto",
    "en la gasolinera",
    "en la estación de servicio",
    "en el museo",
    "en la tienda",
    "en el banco",
    "en el parque de atracciones",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el autobús",
    "en el tren",
    "en el metro",
    "en la gasolinera",
    "en la estación de servicio",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en el aeropuerto",
    "en el centro comercial",
    "en el parque de atracciones",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el colegio",
    "en la universidad",
    "en la estación de tren",
    "en el metro",
    "en el parque",
    "en la playa",
    "en la montaña",
    "en el campo",
    "en el centro comercial",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en el aeropuerto",
    "en la gasolinera",
    "en la estación de servicio",
    "en el museo",
    "en la tienda",
    "en el banco",
    "en el parque de atracciones",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el autobús",
    "en el tren",
    "en el metro",
    "en la gasolinera",
    "en la estación de servicio",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en el aeropuerto",
    "en el centro comercial",
    "en el parque de atracciones",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el colegio",
    "en la universidad",
    "en la estación de tren",
    "en el metro",
    "en el parque",
    "en la playa",
    "en la montaña",
    "en el campo",
    "en el centro comercial",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en el aeropuerto",
    "en el centro comercial",
    "en el parque de atracciones",
    "en la feria",
    "en la peluquería",
    "en la panadería",
    "en la carnicería",
    "en el autobús",
    "en el tren",
    "en el metro",
    "en la gasolinera",
    "en la estación de servicio",
    "en el supermercado",
    "en el restaurante",
    "en el café",
    "en la biblioteca",
    "en la piscina",
    "en el gimnasio",
    "en el estadio",
    "en el cine",
    "en el teatro",
    "en el hospital",
    "en la farmacia",
    "en la iglesia",
    "en la plaza",
    "en mi casa",
    "dentro de mi habitación",
    "en mi sala de estar",
    "en mi cocina",
    "en mi baño",
    "en mi jardín",
    "en mi estudio",
    "en mi terraza",
    "en mi garaje",
    "en mi gimnasio",
    "en mi despacho",
    "en mi sala de juegos",
    "en mi biblioteca",
    "en mi comedor",
    "en mi balcón",
    "en mi cuarto de lavado",
    "en mi patio trasero",
    "en mi ático",
    "en mi sótano",
    "en mi sala de cine",
    "en mi habitación de invitados",
    "en mi sala de música",
    "en mi sala de manualidades",
    "en mi cuarto de baño",
    "en mi vestidor",
    "en mi cocina al aire libre",
    "en mi barbacoa",
    "en mi piscina",
    "en mi jacuzzi",
    "en mi sauna",
    "en mi terraza",
    "en mi invernadero",
    "en mi estudio de arte",
    "en mi taller de bricolaje",
    "en mi sala de yoga",
    "en mi zona de meditación",
    "en mi rincón de lectura",
    "en mi zona de juegos",
    "en mi espacio de trabajo",
    "en mi rincón de relajación",
    "en mi área de entrenamiento",
    "en mi rincón de música",
    "en mi lugar de descanso",
    "en mi rincón de hobbies",
    "en mi zona de entretenimiento",
    "en mi rincón de sueños",
    "en mi espacio creativo",
    "en mi lugar favorito de la casa",
    "en mi oasis personal",
    "en mi refugio acogedor",
    "en mi paraíso privado",
    "en mi rincón especial",
    "en mi lugar de paz",
    "en mi área de inspiración",
    "en mi espacio tranquilo",
    "en mi rincón relajante",
    "en mi santuario personal",
    "en mi espacio íntimo",
    "en mi esquina favorita",
    "en mi sitio de desconexión",
    "en mi rincón de reflexión",
    "en mi área de sueños",
    "en mi lugar secreto",
    "en mi rincón de serenidad",
    "en mi escondite personal",
    "en mi espacio mágico",
    "en mi rincón de alegría",
    "en mi área de creatividad",
    "en mi sitio de calma",
    "en mi rincón acogedor",
    "en mi lugar de descanso",
    "en mi espacio encantador",
    "en mi zona de tranquilidad",
    "en mi rincón de bienestar",
    "en mi área de felicidad",
    "en mi lugar de inspiración",
    "en mi santuario",
    "en mi espacio relajante",
    "en mi rincón acogedor",
    "en mi zona de serenidad",
    "en mi lugar de paz",
    "en mi rincón privado",
    "en mi área de calma",
    "en mi sitio de descanso",
    "en mi rincón especial",
    "en mi espacio tranquilo",
    "en mi santuario personal",
    "en mi lugar íntimo",
    "en mi esquina favorita",
    "en mi sitio de desconexión",
    "en mi rincón de reflexión",
    "en mi área de sueños",
    "en mi lugar secreto",
    "en mi rincón de serenidad",
    "en mi espacio mágico",
    "en mi rincón de alegría",
    "en mi área de creatividad",
    "en mi sitio de calma",
    "en mi rincón acogedor",
    "en mi lugar de descanso",
    "en mi espacio encantador",
    "en mi zona de tranquilidad",
    "en mi rincón de bienestar",
    "en mi área de felicidad",
    "en mi lugar de inspiración",
    "en mi santuario",
    "en mi espacio relajante",
    "en mi rincón acogedor",
    "en mi zona de serenidad",
    "en mi lugar de paz",
    "en mi rincón privado",
    "en mi área de calma",
    "en mi sitio de descanso",
    "en mi rincón especial",
    "en mi espacio tranquilo",
    "dentro de una cueva",
    "dentro de una caja",
    "dentro de un armario",
    "dentro de una maleta",
    "dentro de una botella",
    "dentro de un laberinto",
    "dentro de un túnel",
    "dentro de una burbuja",
    "dentro de un submarino",
    "dentro de un avión",
    "dentro de una mochila",
    "dentro de una bolsa",
    "dentro de una taza",
    "dentro de una caja fuerte",
    "dentro de una iglesia",
    "dentro de una pirámide",
    "dentro de un castillo",
    "dentro de un coche",
    "dentro de un tren",
    "dentro de un autobús",
    "dentro de un barco",
    "dentro de una nave espacial",
    "dentro de una mansión",
    "dentro de una tienda",
    "dentro de una fábrica",
    "dentro de un museo",
    "dentro de un cine",
    "dentro de una biblioteca",
    "dentro de un restaurante",
    "dentro de un hotel",
    "dentro de una escuela",
    "dentro de un hospital",
    "dentro de un zoológico",
    "dentro de un parque de diversiones",
    "dentro de una montaña rusa",
    "dentro de una piscina",
    "dentro de una playa",
    "dentro de una cascada",
    "dentro de un bosque",
    "dentro de una cueva",
    "dentro de una selva",
    "dentro de una tormenta",
    "dentro de una cueva de hielo",
    "dentro de una iglú",
    "sobre una montaña",
    "sobre un rascacielos",
    "sobre una nube",
    "sobre una alfombra",
    "sobre una mesa",
    "sobre un pedestal",
    "sobre un puente",
    "sobre un río",
    "sobre una colina",
    "sobre una torre",
    "sobre un castillo",
    "sobre un árbol",
    "sobre una roca",
    "sobre un barco",
    "sobre una moto",
    "sobre un caballo",
    "sobre un elefante",
    "sobre un avión",
    "sobre una bicicleta",
    "sobre una patineta",
    "sobre una tabla de surf",
    "sobre una valla",
    "sobre una lancha",
    "sobre una silla",
    "sobre una hamaca",
    "sobre una nube de algodón",
    "sobre un arcoíris",
    "bajo el mar",
    "bajo la tierra",
    "bajo un árbol",
    "bajo un puente",
    "bajo un paraguas",
    "bajo una sombrilla",
    "bajo un techo",
    "bajo una manta",
    "bajo una roca",
    "bajo una lámpara",
    "bajo un toldo",
    "bajo un sombrero",
    "bajo una montaña",
    "bajo un lago",
    "bajo una cascada",
    "bajo una mesa",
    "bajo una cama",
    "bajo una silla",
    "bajo una alfombra",
    "bajo una cueva",
    "bajo una carpa",
    "bajo una valla",
    "bajo una cueva de hielo",
    "bajo un iceberg",
    "bajo un cielo estrellado",
    "bajo un paraguas roto",
    "bajo un arcoíris",
    "bajo la lluvia",
    "bajo el sol",
    "bajo la luna",
    "bajo las nubes",
    "bajo la sombra",
    "bajo el agua",
    "bajo la nieve",
    "bajo una tormenta",
    "bajo una avalancha",
    "bajo una fogata",
    "bajo una bandera",
    "bajo una carpa",
    "bajo un cobertizo",
    "bajo un árbol frondoso",
    "bajo una hoja caída",
    "bajo un cielo despejado",
    "bajo una corriente de agua",
    "bajo una luz tenue",
    "bajo una noche estrellada",
    "bajo un mar de estrellas",
    "bajo una capa de nieve",
    "bajo un dosel de árboles",
    "bajo una bóveda celeste",
    "bajo un manto de oscuridad",
    "bajo una llovizna suave",
    "bajo una ráfaga de viento",
    "bajo un manto blanco",
    "bajo un cielo azul",
    "bajo un sol radiante",
    "bajo una luna brillante",
    "bajo un mar en calma",
    "bajo una ola gigante",
    "bajo una avalancha de emociones",
    "bajo un volcán en erupción",
    "bajo una ladera empinada",
    "bajo una montaña sagrada",
    "bajo una jungla exuberante",
    "bajo una catarata imponente",
    "bajo una muralla antigua",
    "bajo una noche estrellada",
    "bajo una carpa de circo",
    "bajo una luz de luna",
    "bajo una fogata",
    "bajo una bandera ondeante",
    "bajo un dosel de árboles",
    "bajo una bóveda celeste",
    "bajo un manto de oscuridad",
    "bajo una llovizna suave",
    "bajo una ráfaga de viento",
    "bajo un manto blanco",
    "bajo un cielo azul",
    "bajo un sol radiante",
    "bajo una luna brillante",
    "bajo un mar en calma",
    "bajo una ola gigante",
    "bajo una avalancha de emociones",
    "bajo un volcán en erupción",
    "en el lago",
    "en el río",
    "entre las algas",
    "bajo el puente",
    "cerca de la orilla",
    "en el estanque",
    "en la piscina",
    "en el arroyo",
    "en el mar",
    "junto a los nenúfares",
    "en la cascada",
    "en el remanso",
    "a lo largo del canal",
    "en el embalse",
    "en la charca",
    "entre las piedras",
    "bajo la sombra de los árboles",
    "en la corriente",
    "entre las hojas",
    "en el agua clara",
    "en el rincón del río",
    "en el estuario",
    "en la poza",
    "en el chorro de agua",
    "en la fuente",
    "en el regato",
    "en la laguna",
    "en la ensenada",
    "en el cenote",
    "entre las olas",
    "en el fondeadero",
    "en el muelle",
    "bajo la lluvia",
    "en el océano",
    "en el riachuelo",
    "en la cascada",
    "entre las piedras del río",
    "en el torrente",
    "en el río tranquilo",
    "en el mar abierto",
    "junto a los nenúfares",
    "en la corriente serpenteante",
    "en el lago cristalino",
    "en la poza profunda",
    "entre las rocas del arroyo",
    "bajo la sombra de los árboles",
    "en el agua clara y fresca",
    "en el rincón del río silencioso",
    "en el estuario de aguas saladas",
    "en la fuente de agua dulce",
    "en el regato angosto",
    "en la laguna serena",
    "en la ensenada escondida",
    "en el cenote sagrado",
    "entre las olas bravas",
    "en el fondeadero seguro",
    "en el muelle abandonado",
];

const palabrasUnicas = [...new Set(arr)];

fs.writeFileSync("llocs.txt", palabrasUnicas.join("\n"));
