//importa el fs
import fs from "fs";

let arr = [
  "tocando el piano",
  "operando un robot",
  "bailando bajo la lluvia",
  "cocinando una cena",
  "diseñando un edificio",
  "nadando",
  "pintando un paisaje",
  "cantando en un concierto",
  "investigando un crimen",
  "corriendo una maratón",
  "haciendo magia",
  "tomando fotos",
  "reparando un coche",
  "construyendo una casa",
  "surfeando",
  "haciendo teatro",
  "descubriendo un tesoro",
  "creando moda",
  "haciendo reír",
  "infiltrándose en una misión",
  "hackeando una computadora",
  "desfilando",
  "escalando",
  "dirigiendo una película",
  "cultivando frutas",
  "apagando incendios",
  "salvando vidas",
  "montando a caballo",
  "reparando un electrodoméstico",
  "defendiendo a los indefensos",
  "podando un jardín",
  "flotando ",
  "luchando ",
  "patinando ",
  "informando las noticias",
  "manejando una motocicleta",
  "enseñando a estudiantes",
  "buceando en aguas profundas",
  "codificando un programa",
  "rescatando a personas atrapadas",
  "entrevistando a celebridades",
  "acelerando en una carrera",
  "plantando flores",
  "flotando en gravedad cero",
  "sazonando una deliciosa comida",
  "programando un software",
  "despegando en un cohete",
  "confeccionando ropa",
  "entretiendo a una audiencia",
  "escalando una pared",
  "entrenando para una competición",
  "compitiendo en una carrera",
  "posando para una sesión de fotos",
  "galopando en un caballo",
  "pirateando un sistema de seguridad",
  "acelerando en una motocicleta",
  "injertando plantas",
  "reeditando un libro",
  "combinando colores",
  "agregando ingredientes",
  "fabricando productos",
  "desarrollando una nueva tecnología",
  "evolucionando una especie",
  "diversificando un portafolio de inversiones",
  "complementando un conjunto de muebles",
  "mejorando una habilidad artística",
  "actualizando un software",
  "duplicando una imagen",
  "copiando un diseño",
  "reproduciendo una obra de arte",
  "improvisando una escena cómica",
  "fusionando estilos de danza",
  "mezclando colores",
  "ensamblando piezas",
  "reproduciendo una canción",
  "grabando un video",
  "involucrando a la comunidad",
  "combinando sabores",
  "agregando detalles",
  "creando un nuevo invento",
  "fabricando productos",
  "desarrollando un plan",
  "evolucionando una especie",
  "diversificando habilidades",
  "investigando un fenómeno",
  "probando una hipótesis",
  "construyendo un puente",
  "resolviendo un enigma",
  "aplicando un tratamiento",
  "implementando nuevas políticas",
  "concluyendo un proyecto",
  "aceptando un desafío",
  "rechazando una oferta",
  "esperando con ansias",
  "anticipando el futuro",
  "preveyendo posibles obstáculos",
  "imaginando mundos",
  "visualizando un futuro próspero",
  "innovando en tecnología",
  "transformando un espacio vacío",
  "modificando un diseño",
  "adaptando una historia",
  "mejorando una técnica",
  "modificando una canción",
  "transformando una receta",
  "construyendo un modelo",
  "destruyendo una construcción",
  "eliminando barreras",
  "desarrollando un proyecto",
  "diseñando una solución",
  "investigando un crimen",
  "descubriendo misterios",
  "explorando mundos",
  "observando la belleza de la naturaleza",
  "experimentando con nuevas técnicas",
  "cuestionando creencias",
  "entendiendo el comportamiento",
  "comprendiendo la complejidad",
  "sabiendo más sobre el pasado",
  "conociendo diferentes culturas",
  "ignorando comentarios negativos",
  "olvidando errores",
  "recordando momentos felices",
  "organizando un evento especial",
  "ordenando elementos",
  "planificando un viaje emocionante",
  "preparando una deliciosa comida",
  "realizando una actuación",
  "tocando el piano",
  "operando un robot",
  "bailando bajo la lluvia",
  "cocinando una cena",
  "diseñando un edificio",
  "nadando",
  "pintando un paisaje",
  "cantando en un concierto",
  "investigando un crimen",
  "corriendo una maratón",
  "haciendo magia",
  "tomando fotos",
  "reparando un coche",
  "construyendo una casa",
  "surfeando",
  "haciendo teatro",
  "descubriendo un tesoro",
  "creando moda",
  "haciendo reír",
  "infiltrándose en una misión",
  "hackeando una computadora",
  "desfilando",
  "escalando",
  "dirigiendo una película",
  "cultivando frutas",
  "apagando incendios",
  "salvando vidas",
  "montando a caballo",
  "reparando un electrodoméstico",
  "defendiendo a los indefensos",
  "podando un jardín",
  "flotando",
  "luchando",
  "patinando",
  "informando las noticias",
  "manejando una motocicleta",
  "enseñando a estudiantes",
  "buceando en aguas profundas",
  "codificando un programa",
  "rescatando a personas atrapadas",
  "entrevistando a celebridades",
  "acelerando en una carrera",
  "plantando flores",
  "flotando en gravedad cero",
  "sazonando una deliciosa comida",
  "programando un software",
  "despegando en un cohete",
  "confeccionando ropa",
  "entretiendo a una audiencia",
  "escalando una pared",
  "entrenando para una competición",
  "compitiendo en una carrera",
  "posando para una sesión de fotos",
  "galopando en un caballo",
  "pirateando un sistema de seguridad",
  "acelerando en una motocicleta",
  "injertando plantas",
  "reeditando un libro",
  "combinando colores",
  "agregando ingredientes",
  "fabricando productos",
  "desarrollando una nueva tecnología",
  "evolucionando una especie",
  "diversificando un portafolio de inversiones",
  "complementando un conjunto de muebles",
  "mejorando una habilidad artística",
  "actualizando un software",
  "duplicando una imagen",
  "copiando un diseño",
  "reproduciendo una obra de arte",
  "improvisando una escena cómica",
  "fusionando estilos de danza",
  "mezclando colores",
  "ensamblando piezas",
  "reproduciendo una canción",
  "grabando un video",
  "involucrando a la comunidad",
  "combinando sabores",
  "agregando detalles",
  "creando un nuevo invento",
  "fabricando productos",
  "desarrollando un plan",
  "evolucionando una especie",
  "diversificando habilidades",
  "investigando un fenómeno",
  "probando una hipótesis",
  "construyendo un puente",
  "resolviendo un enigma",
  "aplicando un tratamiento",
  "implementando nuevas políticas",
  "concluyendo un proyecto",
  "aceptando un desafío",
  "rechazando una oferta",
  "esperando con ansias",
  "anticipando el futuro",
  "preveyendo posibles obstáculos",
  "imaginando mundos",
  "visualizando un futuro próspero",
  "innovando en tecnología",
  "transformando un espacio vacío",
  "modificando un diseño",
  "adaptando una historia",
  "mejorando una técnica",
  "modificando una canción",
  "transformando una receta",
  "construyendo un modelo",
  "destruyendo una construcción",
  "eliminando barreras",
  "desarrollando un proyecto",
  "diseñando una solución",
  "investigando un crimen",
  "descubriendo misterios",
  "explorando mundos",
  "observando la belleza de la naturaleza",
  "experimentando con nuevas técnicas",
  "cuestionando creencias",
  "entendiendo el comportamiento",
  "comprendiendo la complejidad",
  "sabiendo más sobre el pasado",
  "conociendo diferentes culturas",
  "ignorando comentarios negativos",
  "olvidando errores",
  "recordando momentos felices",
  "organizando un evento especial",
  "ordenando elementos",
  "planificando un viaje emocionante",
  "preparando una deliciosa comida",
  "realizando una actuación",
  "caminando",
  "leyendo",
  "cantando",
  "bailando",
  "corriendo",
  "nadando",
  "escribiendo",
  "tocando",
  "pintando",
  "cocinando",
  "dibujando",
  "estudiando",
  "riendo",
  "hablando",
  "gritando",
  "saltando",
  "volando",
  "navegando",
  "viajando",
  "explorando lugares",
  "programando software",
  "hackeando sistemas",
  "despertando temprano",
  "soñando despierto",
  "descansando un poco",
  "trabajando duro",
  "descubriendo talentos",
  "observando las estrellas",
  "resolviendo problemas",
  "aprendiendo idiomas",
  "enseñando en la escuela",
  "reparando máquinas",
  "construyendo casas",
  "creando arte",
  "innovando tecnología",
  "compartiendo conocimientos",
  "inspirando a otros",
  "liderando equipos",
  "ayudando amigos",
  "apoyando en momentos difíciles",
  "animando a su equipo",
  "comprando regalos",
  "vendiendo productos",
  "convenciendo con argumentos",
  "celebrando cumpleaños",
  "disfrutando la comida",
  "ejercitando diariamente",
  "practicando música",
  "meditando para relajarse",
  "relajando en la playa",
  "reflexionando sobre la vida",
  "sonriendo siempre",
  "suspirando aliviado",
  "sintiendo empatía",
  "entendiendo problemas",
  "aceptando desafíos",
  "rechazando ofertas",
  "olvidando el pasado",
  "perdonando errores",
  "recordando buenos momentos",
  "agradeciendo el apoyo",
  "celebrando éxitos",
  "disculpando rápidamente",
  "emocionando a otros",
  "planificando el futuro",
  "soportando dificultades",
  "animando a todos",
  "agotando energías",
  "consolando a amigos",
  "sorprendiendo con regalos",
  "rescatando a animales",
  "socorriendo a personas",
  "dirigiendo reuniones",
  "guiando turistas",
  "compartiendo secretos",
  "descubriendo maravillas",
  "explorando horizontes",
  "entrevistando a artistas",
  "observando la naturaleza",
  "apreciando el arte",
  "organizando eventos",
  "protegiendo el ambiente",
  "representando causas",
  "resolviendo conflictos",
  "mostrando habilidades",
  "preparando cenas",
  "validando sentimientos",
  "actualizando conocimientos",
  "mejorando habilidades",
  "agradeciendo gestos",
  "valorando contribuciones",
  "fomentando creatividad",
  "aplaudiendo esfuerzos",
  "colaborando en proyectos",
  "compitiendo sanamente",
  "cooperando con otros",
  "admirando talento",
  "felicitando logros",
  "motivando a superarse",
  "sorprendiendo gratamente",
  "aplaudiendo buenas acciones",
  "dirigiendo grupos",
  "disfrutando momentos",
  "ejecutando estrategias",
  "planificando actividades",
  "sintiendo gratitud",
  "trabajando arduamente",
  "bailando con pasión",
  "cantando con alegría",
  "actuando en teatro",
  "tocando instrumentos",
  "luchando por ideales",
  "nadando en aguas claras",
  "riendo con amigos",
  "pintando paisajes",
  "dibujando retratos",
  "corriendo en competencias",
  "jugando divertidos juegos",
  "viviendo nuevas experiencias",
  "aprendiendo cada día",
  "enseñando con entusiasmo",
  "viajando a lugares exóticos",
  "creciendo personalmente",
  "soñando con grandes proyectos",
  "compartiendo momentos especiales",
  "ayudando a otros",
  "amando a su familia",
  "inspirando con acciones",
  "sirviendo con dedicación",
  "construyendo su futuro",
  "trabajando juntos",
  "descubriendo avances",
  "explorando campos",
  "investigando temas",
  "solucionando desafíos",
  "liderando con pasión",
  "enseñando con paciencia",
  "comunicando con claridad",
  "resolviendo problemas",
  "mejorando constantemente",
  "creando juntos",
  "colaborando en proyectos",
  "innovando en tecnología",
  "compartiendo experiencias",
  "celebrando momentos",
  "apoyando a quienes lo necesitan",
  "respetando a los demás",
  "agradeciendo el apoyo",
  "animando a otros",
  "fomentando la creatividad",
  "conectando con personas",
  "agrandando su red de contactos",
  "reconociendo a otros",
  "aceptando desafíos",
  "creciendo como persona",
  "mostrando gratitud",
  "inspirando con su ejemplo",
  "compartiendo conocimientos",
  "guiando en momentos difíciles",
  "descubriendo nuevas formas de ayudar",
  "sirviendo a la comunidad",
  "protegiendo el ambiente",
  "mejorando día a día",
  "celebrando cada logro",
  "compartiendo momentos especiales",
  "agradeciendo el apoyo",
  "animando a seguir adelante",
  "fomentando un ambiente positivo",
  "mostrando gratitud",
  "guiando en momentos difíciles",
  "creciendo en sabiduría",
  "sintiendo empatía",
  "transformando vidas",
  "construyendo una maqueta",
  "cosechando frutas",
  "esculpinedo una escultura",
  "explorando una cueva",
  "corriendo en una cinta",
  "caminando por la playa",
  "estudiando para un examen",
  "redactando un informe",
  "componiendo una canción",
  "resolviendo un rompecabezas",
  "haciendo malabares",
  "observando las estrellas",
  "pescando en un río",
  "entrenando a un equipo",
  "aterrizando en un aeropuerto",
  "planificando una estrategia",
  "bailando con gracia",
  "creando un collage",
  "estudiando el comportamiento animal",
  "observando aves en su hábitat",
  "mezclando ingredientes",
  "aplicando maquillaje",
  "diseñando una página web",
  "resolviendo un problema matemático",
  "navegando por internet",
  "editando un video",
  "tocando un instrumento musical",
  "realizando un experimento",
  "leyendo un libro interesante",
  "disfrutando de un atardecer",
  "jugando en el parque",
  "entusiasmándose con una película",
  "preparando una sorpresa",
  "cocinando en familia",
  "decorando una habitación",
  "improvisando un discurso",
  "reparando una bicicleta",
  "escribiendo un poema",
  "comprando regalos para amigos",
  "organizando una fiesta sorpresa",
  "estudiando el arte del origami",
  "practicando yoga en la playa",
  "bordando un mantel",
  "pintando un mural en la calle",
  "corriendo en el bosque",
  "disfrutando de una comida gourmet",
  "explorando un museo",
  "resolviendo un enigma",
  "volando una cometa en el parque",
  "realizando acrobacias en patines",
  "contemplando una puesta de sol",
  "investigando una teoría científica",
  "estudiando el lenguaje de las abejas",
  "aprendiendo técnicas de meditación",
  "escuchando música relajante",
  "jugando con una mascota",
  "cocinando una receta exótica",
  "buceando en un arrecife de coral",
  "navegando en un velero",
  "construyendo un castillo de arena",
  "bailando en una fiesta",
  "enseñando a bailar salsa",
  "disfrutando de un concierto en vivo",
  "practicando deportes acuáticos",
  "escuchando un podcast interesante",
  "compartiendo conocimientos en un taller",
  "ayudando a limpiar el medio ambiente",
  "participando en una campaña benéfica",
  "colaborando en un proyecto comunitario",
  "organizando un evento cultural",
  "presentando una obra de teatro",
  "inspirando a otros con tus palabras",
  "navegando en un barco de vela",
  "explorando una ciudad desconocida",
  "planificando un viaje de aventura",
  "montando en una montaña rusa",
  "conquistando tus miedos",
  "compartiendo tus habilidades con otros",
  "descubriendo talentos ocultos",
  "participando en una competencia deportiva",
  "expresando tus emociones a través del arte",
  "mejorando tus habilidades de comunicación",
  "cosechando los frutos de tu esfuerzo",
  "cultivando la paciencia y la perseverancia",
  "aprendiendo de tus errores y fracasos",
  "compartiendo alegrías y tristezas con amigos",
  "viviendo el momento presente",
  "disfrutando de la naturaleza y sus maravillas",
  "apreciando la belleza en las pequeñas cosas",
  "fortaleciendo tus lazos familiares",
  "comprendiendo la diversidad del mundo",
  "descubriendo la magia de la vida cotidiana",
  "aceptando los desafíos con valentía",
  "transformando obstáculos en oportunidades",
  "abrazando el cambio y la incertidumbre",
  "creciendo y evolucionando como persona",
  "construyendo recuerdos inolvidables",
  "inspirando a otros con tu ejemplo",
  "explorando tus talentos y pasiones",
  "cultivando la empatía y el respeto hacia los demás",
  "conectando con tu ser interior y espiritualidad",
  "descubriendo el poder de la mente y el pensamiento positivo",
  "compartiendo amor y compasión con el mundo",
  "disfrutando de la belleza y diversidad cultural",
  "aprendiendo de las experiencias de vida",
  "brindando apoyo y ayuda a quienes lo necesitan",
  "compartiendo risas y momentos de felicidad",
  "expresando gratitud y aprecio por la vida",
  "abrazando la aventura y la exploración",
  "cultivando la resiliencia y la fuerza interna",
  "construyendo relaciones auténticas y significativas",
  "aprendiendo a perdonar y soltar rencores",
  "disfrutando del silencio y la tranquilidad",
  "cultivando la creatividad y la imaginación",
  "aceptando la vulnerabilidad y la imperfección",
  "transformando la adversidad en aprendizaje",
  "conectando con la naturaleza y el entorno",
  "compartiendo el conocimiento y la sabiduría",
  "inspirando y motivando a otros a seguir sus sueños",
  "viviendo con pasión y propósito",
  "disfrutando de cada instante como si fuera el último",
  "tocando el piano",
  "operando un robot",
  "bailando bajo la lluvia",
  "cocinando una cena",
  "diseñando un edificio",
  "nadando en el mar",
  "pintando un paisaje",
  "cantando en un concierto",
  "investigando un crimen",
  "corriendo una maratón",
  "haciendo magia",
  "tomando fotos",
  "reparando un coche",
  "construyendo una casa",
  "surfeando en el océano",
  "actuando en el teatro",
  "descubriendo un tesoro",
  "creando moda",
  "haciendo reír a la gente",
  "infiltrándose en una misión secreta",
  "hackeando una computadora",
  "desfilando en una pasarela",
  "escalando una montaña",
  "dirigiendo una película",
  "cultivando frutas en el huerto",
  "apagando incendios",
  "salvando vidas",
  "montando a caballo",
  "reparando un electrodoméstico",
  "defendiendo a los indefensos",
  "podando un jardín",
  "flotando en el agua",
  "luchando por la justicia",
  "patinando en la pista",
  "informando las noticias",
  "manejando una motocicleta",
  "enseñando a estudiantes",
  "buceando en aguas profundas",
  "codificando un programa",
  "rescatando a personas atrapadas",
  "entrevistando a celebridades",
  "acelerando en una carrera",
  "plantando flores en el jardín",
  "flotando en gravedad cero",
  "sazonando una deliciosa comida",
  "programando un software",
  "despegando en un cohete",
  "confeccionando ropa a mano",
  "entretiendo a una audiencia",
  "escalando una pared rocosa",
  "entrenando para una competición",
  "compitiendo en una carrera emocionante",
  "posando para una sesión de fotos",
  "galopando en un caballo blanco",
  "pirateando un sistema de seguridad",
  "acelerando en una motocicleta rápida",
  "injertando plantas en el jardín",
  "reeditando un libro clásico",
  "combinando colores vibrantes",
  "agregando ingredientes frescos",
  "fabricando productos innovadores",
  "desarrollando una nueva tecnología",
  "evolucionando una especie animal",
  "diversificando un portafolio de inversiones",
  "complementando un conjunto de muebles",
  "mejorando una habilidad artística",
  "actualizando un software importante",
  "duplicando una imagen perfectamente",
  "copiando un diseño original",
  "reproduciendo una obra de arte famosa",
  "improvisando una escena cómica",
  "fusionando estilos de danza diferentes",
  "mezclando colores creativos",
  "ensamblando piezas complicadas",
  "reproduciendo una canción famosa",
  "grabando un video emocionante",
  "involucrando a la comunidad local",
  "combinando sabores exquisitos",
  "agregando detalles interesantes",
  "creando un nuevo invento increíble",
  "desarrollando un plan estratégico",
  "diversificando habilidades profesionales",
  "investigando un fenómeno misterioso",
  "probando una hipótesis científica",
  "construyendo un puente sólido",
  "resolviendo un enigma complicado",
  "aplicando un tratamiento médico",
  "implementando nuevas políticas sociales",
  "concluyendo un proyecto exitoso",
  "aceptando un desafío emocionante",
  "rechazando una oferta tentadora",
  "esperando con ansias una oportunidad",
  "anticipando el futuro incierto",
  "preveyendo posibles obstáculos",
  "imaginando mundos fantásticos",
  "visualizando un futuro próspero",
  "innovando en tecnología avanzada",
  "transformando un espacio vacío en hogar",
  "modificando un diseño existente",
  "adaptando una historia clásica",
  "mejorando una técnica valiosa",
  "modificando una canción popular",
  "transformando una receta tradicional",
  "construyendo un modelo a escala",
  "destruyendo una construcción antigua",
  "eliminando barreras sociales",
  "desarrollando un proyecto ambicioso",
  "diseñando una solución creativa",
  "descubriendo misterios ocultos",
  "explorando mundos desconocidos",
  "observando la belleza de la naturaleza",
  "experimentando con nuevas técnicas",
  "cuestionando creencias arraigadas",
  "entendiendo el comportamiento humano",
  "comprendiendo la complejidad del universo",
  "sabiendo más sobre el pasado histórico",
  "conociendo diferentes culturas fascinantes",
  "ignorando comentarios negativos",
  "olvidando errores pasados",
  "recordando momentos felices",
  "organizando un evento especial",
  "ordenando elementos esenciales",
  "planificando un viaje emocionante",
  "preparando una deliciosa comida casera",
  "realizando una actuación apasionante",
  "flotando en el aire",
  "luchando por un mundo mejor",
  "patinando sobre hielo",
  "caminando bajo la luna",
  "leyendo un libro inspirador",
  "cantando con pasión",
  "bailando con gracia",
  "corriendo hacia el futuro",
  "escribiendo con creatividad",
  "tocando una melodía encantadora",
  "pintando un cuadro magnífico",
  "cocinando con amor",
  "dibujando con destreza",
  "estudiando con dedicación",
  "riendo con alegría",
  "hablando con sinceridad",
  "gritando de emoción",
  "saltando de felicidad",
  "volando hacia nuevas alturas",
  "navegando en aguas desconocidas",
  "viajando a destinos emocionantes",
];

const palabrasUnicas = [...new Set(arr)];

fs.writeFileSync("accions.txt", palabrasUnicas.join("\n"));

